name: Push-to-EC2

# Trigger deployment on push to both main and staging branches
on:
  push:
    branches:
      - main
     

jobs:
  deploy:
    name: Deploy to EC2 on main or staging branch push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Deploy to Server 1
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}

      - name: Executing remote SSH commands using SSH key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo apt-get -y update
            sudo apt-get install -y apache2
            sudo systemctl start apache2
            sudo systemctl enable apache2
            cd home
            sudo git checkout -b staging
            git clone -b staging https://github.com/ahsandev17/ResumeCV.git
            sudo mv * /var/www/html
            cd /var/www/html
            sudo chmod 777 script.sh
            sudo ./script.sh
            sudo touch gitFile3.txt
